//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanFoods_API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.GiaoHangs = new HashSet<GiaoHang>();
            this.GioHangs = new HashSet<GioHang>();
        }
    
        public int idDonHang { get; set; }
        public Nullable<int> MaSoDonHang { get; set; }
        public Nullable<int> idKhachHang { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayXacNhanDonHang { get; set; }

        [NotMapped]
        public string DeletedOrderItemIDs { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoHang> GiaoHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
    }
}
