//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanFoods_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoHang
    {
        public int idGiaoHang { get; set; }
        public Nullable<int> idDonHang { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
